"""Learn the majority Primary/Secondary type per DOI repository prefix.

    python scripts/build_prefix_types.py --split splits/dev.txt

Writes models/doi_prefix_types.txt. Learned from dev only. A prefix needs at
least --min-support gold citations before it is trusted to override the generic
rule; below that the evidence is too thin to beat format+location.
"""

from __future__ import annotations

import argparse
import os
from collections import Counter, defaultdict
from pathlib import Path

import _paths  # noqa: F401

from mdc.data import gold_triples, load_labels
from mdc.repositories import doi_prefix
from mdc.split import read_split


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir", default=os.environ.get("MDC_DATA_DIR", "data"))
    ap.add_argument("--split", default="splits/dev.txt")
    ap.add_argument("--out", default="models/doi_prefix_types.txt")
    ap.add_argument("--min-support", type=int, default=5)
    args = ap.parse_args()

    split = read_split(args.split)
    labels = load_labels(Path(args.data_dir) / "train_labels.csv")
    counts: defaultdict[str, Counter] = defaultdict(Counter)
    for article_id, dataset_id, ty in gold_triples(labels):
        if article_id in split:
            prefix = doi_prefix(dataset_id)
            if prefix:
                counts[prefix][ty] += 1

    kept = {
        prefix: c.most_common(1)[0][0]
        for prefix, c in counts.items()
        if sum(c.values()) >= args.min_support
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# majority type per DOI prefix, from {Path(args.split).name}",
        "# generated by scripts/build_prefix_types.py -- do not hand-edit",
        f"# min support {args.min_support}; {len(kept)} of {len(counts)} prefixes qualify",
        "",
    ]
    for prefix, ty in sorted(kept.items(), key=lambda kv: -sum(counts[kv[0]].values())):
        c = counts[prefix]
        lines.append(f"{prefix} {ty}  # P={c['Primary']} S={c['Secondary']}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(kept)} prefixes with >= {args.min_support} support -> {out}")
    for line in lines[4:12]:
        print("  " + line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
