"""Learn the data-repository DOI prefix allowlist from a split.

    python scripts/build_allowlist.py --split splits/dev.txt

Writes models/doi_prefix_allowlist.txt. Learned from dev only -- never from
holdout, which has to stay an untouched estimate. Re-run this if the split
changes; the output is committed so every score in the README is reproducible.
"""

from __future__ import annotations

import argparse
import os
from collections import Counter
from pathlib import Path

import _paths  # noqa: F401

from mdc.data import gold_triples, load_labels
from mdc.repositories import APRIORI_PREFIXES, doi_prefix
from mdc.split import read_split


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir", default=os.environ.get("MDC_DATA_DIR", "data"))
    ap.add_argument("--split", default="splits/dev.txt")
    ap.add_argument("--out", default="models/doi_prefix_allowlist.txt")
    args = ap.parse_args()

    split = read_split(args.split)
    labels = load_labels(Path(args.data_dir) / "train_labels.csv")
    counts: Counter[str] = Counter()
    for article_id, dataset_id, _ in gold_triples(labels):
        if article_id in split:
            prefix = doi_prefix(dataset_id)
            if prefix:
                counts[prefix] += 1

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# DOI prefixes of gold data citations in {Path(args.split).name}",
        "# generated by scripts/build_allowlist.py -- do not hand-edit",
        f"# {len(counts)} prefixes covering {sum(counts.values())} gold DOI citations",
        "",
    ]
    lines += [f"{prefix}  # {n}" for prefix, n in counts.most_common()]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(counts)} prefixes from {sum(counts.values())} gold DOIs -> {out}")
    print(f"a-priori prefixes not seen in this split: "
          f"{sorted(APRIORI_PREFIXES - set(counts))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
